#                                         #
#                PvPBuilder               #
#                   by                    #
#                MathiasMC                #
#  Any ideas for the plugin or need help? #
#           contact me on spigot          #
#                                         #

# Check for updates on startup?
update-check: true