#                                         #
#                PvPBuilder               #
#                   by                    #
#                MathiasMC                #
#  Any ideas for the plugin or need help? #
#           contact me on spigot          #
#                                         #

# Check for updates on startup?
update-check: true

wand:
  material: '280:0'
  name: '&6PvPBuilder &bWand'
  lores:
    - '&aThis tool is used to select points'